### ISSUE TITLE
error after make install complete

### ISSUE THREAD

**Issue by Jv187** [bivav/iqoptionLinux#1]
cancel

**Comment by Jv187** [comment]
> msiextract: error while loading shared libraries: libmsi.so.0: cannot open shared object file: No such file or directory

its solved by reinstall msitools and can execute msiextract, but when the program files created, the IQOption.exe appear with single quote ('IQ Option.exe') when tried to launch it by wine start 'IQ Option.exe' its forced close

**Comment by bivav** [comment]
@Jv187 I know it's a pretty late reply but I haven't maintained this repo for quite a while since I stopped using IQOption.
Can look into this if you still require it.
